---
- hosts: all
  vars:
    ouName: # mandatory
    path: # mandatory
  tasks:
  - name: createOU
    win_shell: New-ADOrganizationalUnit -Name {{ouName|mandatory}} -Path "{{path|mandatory}}"
    register: commandExecuted
  - debug:
      var: commandExecuted
