---
- hosts: all
  gather_facts: no
  vars:
    cont_names: ["defaultContainer"]
    host_ports: ["8080"]
    images: ["vulnerables/cve-2014-6271"]
  become: yes
  tasks:

  - name: Install Pip
    package: name='{{item}}' state=latest
    with_items:
      - python-pip
      - python-dev
      - build-essential

  - name: Install Docker for pip
    pip:
      name: docker-py


  - name: Execute the command in remote shell; stdout goes to the specified file on the remote.
    shell: curl -ssl https://get.docker.com/ | sh
    args:
      warn: False

  - name: Ensure docker deamon is running
    service:
      name: docker
      state: started
    become: true

  - docker_container:
      name: "{{ item[0] }}"
      image: "{{ item[2] }}"
      ports:
        - "{{ item[1] }}:80"
    with_together:
        - "{{ cont_names }}"
        - "{{ host_ports }}"
        - "{{ images }}"